name: Test Action
on:
  push:
    branches: [main,master]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run tests
      run: |
        # Thực hiện các lệnh kiểm tra ở đây
        echo "Running tests..."
        pytest
        
    - name: Build and deploy
      run: |
        # Thực hiện quy trình xây dựng và triển khai ở đây
        echo "Building and deploying..."
        ./build.sh
        ./deploy.sh