name: Test Action
on:
  push:
    branches: [main,master]
jobs:
  test:
    name: Chạy thử
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Cài đặt các phụ thuộc
      run: npm install
      
    - name: Chạy các bài kiểm tra
      run: npm test